name: Build and push to ECR

on:
    push:
        # pull_requests:
        #     branches: [ 'main', 'dev']
      branches: ['main']
permissions:
     id-token: write
     contents: read
  
jobs:
    build_scan:
         runs-on: ubuntu-latest
         steps:
             - name:  Checkout the Code
               uses:  actions/checkout@v7
             - name:  Trivy build_scan
               uses:  aquasecurity/trivy-action@v0.36.0
               with:
                 scan-type: 'fs'
                 severity: HIGH,CRITICAL
                 exit-code: 1
             - name: Build Docker Image
               run: docker build -t ${{ secrets.ECR_REPO }}/myrepo:latest .
             - name:  Scan image with Trivy 
               uses: aquasecurity/trivy-action@v0.36.0 
               with: 
                  image-ref: ${{ secrets.ECR_REPO }}/myrepo:latest
                  format: table 
                  exit-code: 0 
                  ignore-unfixed: true 
                  severity: CRITICAL,HIGH
             - name: Configure AWS credentials
               uses: aws-actions/configure-aws-credentials@v4 # More information on this action can be found below in the 'AWS Credentials' section
               with:
                 role-to-assume: ${{ secrets.AWS_ROLE }}
                 aws-region: us-east-1
             - name: Login to Amazon ECR
               id: login-ecr
               uses: aws-actions/amazon-ecr-login@v2

             - name: push image to ecr
               run: docker push  ${{ secrets.ECR_REPO }}/myrepo:latest
    
    
    Deploy_to_ecs:
        needs: build_scan
        runs-on: ubuntu-latest
        steps:
            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4 # More information on this action can be found below in the 'AWS Credentials' section
              with:
                 aws-region: us-east-1
                 role-to-assume: ${{ secrets.AWS_ROLE }}
              - name: Render new task definition
                        id: render-task-def
                        uses: aws-actions/amazon-ecs-render-task-definition@v1
                        with:
                          task-definition: .github/task-definition.json
                          container-name: myrepo
                          image: ${{ secrets.ECR_REPO }}/myrepo:latest

        
            - name: Deploy to ECS
              uses: aws-actions/amazon-ecs-deploy-task-definition@v2
              with:
              task-definition: ${{ steps.render-task-def.outputs.task-definition }}
              service: myrepo_task-service-ki6mfw5h
              cluster: my_action
              wait-for-service-stability: true
        